name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: omega-flow/lean

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install elan (Lean version manager)
        run: |
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Display Lean version
        run: lean --version

      - name: Build with Lake
        run: lake build
